# Generated by Django 5.2 on 2025-05-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='degree',
            field=models.CharField(blank=True, choices=[('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(blank=True, choices=[('computer_science', 'Computer Science'), ('engineering', 'Engineering'), ('business', 'Business'), ('finance', 'Finance'), ('psychology', 'Psychology'), ('medicine', 'Medicine'), ('arts', 'Arts'), ('education', 'Education'), ('law', 'Law'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
