# Generated by Django 5.2 on 2025-05-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_bio_remove_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, help_text='Your Instagram username (without @)', max_length=30, null=True),
        ),
    ]
